#!/usr/bin/env python3
"""Build data.js for the ZAP Browser from the ZAP project CSV and CD boundaries.

Usage: python3 build.py [path/to/ZAP_project_data.csv]
Defaults to the newest "Zoning_Application_Portal*.csv" in this folder.
"""
import csv
import glob
import json
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
BORO_PREFIX = {1: "M", 2: "X", 3: "K", 4: "Q", 5: "R"}
BORO_NAME = {1: "Manhattan", 2: "Bronx", 3: "Brooklyn", 4: "Queens", 5: "Staten Island"}
# Statuses that count as "open" applications.
OPEN_STATUSES = {"Active", "On-Hold"}
FIELDS = [
    "project_id", "project_name", "project_brief", "project_status", "public_status",
    "ulurp_non", "actions", "ulurp_numbers", "ceqr_type", "primary_applicant",
    "applicant_type", "borough", "community_district", "current_milestone",
    "current_milestone_date", "app_filed_date", "noticed_date", "certified_referred",
    "mih_flag",
]


def cd_code(borocd):
    boro, num = divmod(int(borocd), 100)
    return f"{BORO_PREFIX[boro]}{num:02d}"


def round_coords(coords, nd=5):
    if isinstance(coords[0], (int, float)):
        return [round(coords[0], nd), round(coords[1], nd)]
    return [round_coords(c, nd) for c in coords]


def main():
    csv_path = sys.argv[1] if len(sys.argv) > 1 else max(
        glob.glob(os.path.join(HERE, "Zoning_Application_Portal*.csv")), key=os.path.getmtime)

    projects = []
    with open(csv_path, encoding="utf-8-sig", newline="") as f:
        for row in csv.DictReader(f):
            if row["project_status"] not in OPEN_STATUSES:
                continue
            p = {k: row[k].strip() for k in FIELDS if row.get(k, "").strip()}
            p["cds"] = [c.strip() for c in row["community_district"].split(",") if c.strip()]
            projects.append(p)

    with open(os.path.join(HERE, "data", "community_districts.geojson")) as f:
        gj = json.load(f)
    features = []
    for feat in gj["features"]:
        borocd = int(feat["properties"]["BoroCD"])
        num = borocd % 100
        features.append({
            "type": "Feature",
            "properties": {
                "code": cd_code(borocd),
                "boro": BORO_NAME[borocd // 100],
                "num": num,
                # 55+ are joint interest areas (large parks, airports) rather than boards.
                "jia": num > 20,
            },
            "geometry": {"type": feat["geometry"]["type"],
                         "coordinates": round_coords(feat["geometry"]["coordinates"])},
        })

    out = os.path.join(HERE, "data.js")
    with open(out, "w") as f:
        f.write("// Generated by build.py — do not edit by hand.\n")
        f.write(f"window.ZAP_SOURCE = {json.dumps(os.path.basename(csv_path))};\n")
        f.write("window.ZAP_PROJECTS = " + json.dumps(projects, separators=(",", ":")) + ";\n")
        f.write("window.CD_BOUNDARIES = " + json.dumps(
            {"type": "FeatureCollection", "features": features}, separators=(",", ":")) + ";\n")
    print(f"Wrote {out}: {len(projects)} open projects, {len(features)} districts")


if __name__ == "__main__":
    main()
